### Pandas :

Pandas is an open-source Python library used for data analysis and manipulation. It provides fast, flexible, and easy-to-use data structures for working with structured data such as tables, spreadsheets, and databases.

In [1]:
import pandas as pd

In [2]:
# Series 

import pandas as pd
data =[1,2,3,4,5,6]
series =pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
# Create a series From dicstionary

Data ={"a":1,"b":2,"c":3}

dic_series =pd.Series(Data)
print(dic_series)

a    1
b    2
c    3
dtype: int64

In [4]:
data =([10,20,30])
index=['a','b','c']

pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [5]:
# Data Fram
data ={
    "Name":['Ashish','Aman','Jack'],
    "Age":[20,22,24],
    "city":['Raj','Raj','Nework'],
}
df = pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age    city
0  Ashish   20     Raj
1    Aman   22     Raj
2    Jack   24  Nework
<class 'pandas.DataFrame'>

In [6]:
import numpy as np
np.array(df)

array([['Ashish', 20, 'Raj'],
       ['Aman', 22, 'Raj'],
       ['Jack', 24, 'Nework']], dtype=object)

In [7]:
# creat a data frame list domanstrate
data=[
    { "Name":'Ashish','age':20,'city':"rajasthan"},
    { "Name":'Aman','age':22,'city':"delhi"},
    { "Name":'rancho','age':24,'city':"caleforniya"},
]

df =pd.DataFrame(data)
print(df)

     Name  age         city
0  Ashish   20    rajasthan
1    Aman   22        delhi
2  rancho   24  caleforniya

In [8]:
# Read the csv file
df =pd.read_csv('sales.csv')
df.head(5)

   order_id        date     product region  quantity  unit_price  total_sales
0         1  2024-05-20  Smartphone  South         1        1568         1568
1         2  2024-02-22  Headphones  North         3        1558         4674
2         3  2024-01-16  Smartwatch  North         7         115          805
3         4  2024-11-04  Headphones  North         4        1084         4336
4         5  2024-11-28      Camera   West         4        1516         6064

In [9]:
df.tail()

    order_id        date     product region  quantity  unit_price  total_sales
95        96  2024-10-02       Mouse  South         1        1114         1114
96        97  2024-12-06    Keyboard   East         7         193         1351
97        98  2024-03-04  Smartwatch   East         6        1408         8448
98        99  2024-07-28      Camera   East         5        1415         7075
99       100  2024-03-06       Mouse  South         5        1185         5925

In [10]:
# accessing from data in dataframe
df

    order_id        date     product region  quantity  unit_price  total_sales
0          1  2024-05-20  Smartphone  South         1        1568         1568
1          2  2024-02-22  Headphones  North         3        1558         4674
2          3  2024-01-16  Smartwatch  North         7         115          805
3          4  2024-11-04  Headphones  North         4        1084         4336
4          5  2024-11-28      Camera   West         4        1516         6064
..       ...         ...         ...    ...       ...         ...          ...
95        96  2024-10-02       Mouse  South         1        1114         1114
96        97  2024-12-06    Keyboard   East         7         193         1351
97        98  2024-03-04  Smartwatch   East         6        1408         8448
98        99  2024-07-28      Camera   East         5        1415         7075
99       100  2024-03-06       Mouse  South         5        1185         5925

[100 rows x 7 columns]

In [11]:
# Accesing data from data frame
df

    order_id        date     product region  quantity  unit_price  total_sales
0          1  2024-05-20  Smartphone  South         1        1568         1568
1          2  2024-02-22  Headphones  North         3        1558         4674
2          3  2024-01-16  Smartwatch  North         7         115          805
3          4  2024-11-04  Headphones  North         4        1084         4336
4          5  2024-11-28      Camera   West         4        1516         6064
..       ...         ...         ...    ...       ...         ...          ...
95        96  2024-10-02       Mouse  South         1        1114         1114
96        97  2024-12-06    Keyboard   East         7         193         1351
97        98  2024-03-04  Smartwatch   East         6        1408         8448
98        99  2024-07-28      Camera   East         5        1415         7075
99       100  2024-03-06       Mouse  South         5        1185         5925

[100 rows x 7 columns]

In [12]:
df['Name']

KeyError: 'Name'

In [ ]:
df.loc[0]  # loc are use to pikup the value of Row

Name    Ashish
Age         20
city       Raj
Name: 0, dtype: object

In [ ]:
df.iloc[0] # thet be pickup the coloumn value

Name    Ashish
Age         20
city       Raj
Name: 0, dtype: object

In [ ]:
df

     Name  Age    city
0  Ashish   20     Raj
1    Aman   22     Raj
2    Jack   24  Nework

In [ ]:
## Accesing specifying element
df.at[0,'Age'] # at are basically to use update a single value

np.int64(20)

In [ ]:
df.at[1,'Name']

'Aman'

In [ ]:
## accesing specifying element by iat
df.iat[1,2]

'Raj'

In [ ]:
## Data manuplation  With Data Frame

## Adding a new column
df['Salary']=[2000,4000,5000]
df

     Name  Age    city  Salary
0  Ashish   20     Raj    2000
1    Aman   22     Raj    4000
2    Jack   24  Nework    5000

In [ ]:
# Removing the data ya column and row
# df.drop('Salary',axis=1) #  it is not permanet it's temprary

df.drop('Salary',axis=1,inplace=True) #when you get permantly to use .inplace=

In [ ]:
df

     Name  Age    city
0  Ashish   20     Raj
1    Aman   22     Raj
2    Jack   24  Nework

In [ ]:
# Add age or increse it so 

df['Age']=df['Age']+1
df

     Name  Age    city
0  Ashish   21     Raj
1    Aman   23     Raj
2    Jack   25  Nework

In [ ]:
df = pd.read_csv('sales.csv')
df.head(5)

   order_id        date     product region  quantity  unit_price  total_sales
0         1  2024-05-20  Smartphone  South         1        1568         1568
1         2  2024-02-22  Headphones  North         3        1558         4674
2         3  2024-01-16  Smartwatch  North         7         115          805
3         4  2024-11-04  Headphones  North         4        1084         4336
4         5  2024-11-28      Camera   West         4        1516         6064

In [ ]:
# Display the each coulmn
# print("Data type \n :",df.dtypes)

# Describe Data frame 
# print("statick summery :\n", df.describe)

# group by the argument 
grouped = df.groupby('quantity')['unit_price'].mean()
print('mean of value : \n',grouped)

mean of value :
 quantity
1     1280.090909
2     1249.636364
3      841.000000
4      922.272727
5      665.363636
6     1144.555556
7      954.000000
8     1017.714286
9      800.454545
10     862.428571
Name: unit_price, dtype: float64