In [2]:
import pandas as pd

In [3]:
df =pd.read_csv('bank.csv')
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP00100,Female,NaN,1,Not Graduate,No,17813,4645,488.0,NaN,NaN,Semiurban,Y
1,LP00101,Female,No,1,Not Graduate,NaN,22859,3364,NaN,480.0,0.0,Urban,N
2,LP00102,Male,Yes,2,Not Graduate,Yes,22555,6803,NaN,240.0,NaN,Semiurban,N
3,LP00103,Female,Yes,2,Not Graduate,NaN,4177,3235,NaN,240.0,1.0,Semiurban,N
4,LP00104,Male,No,0,Graduate,No,3175,3400,244.0,480.0,0.0,Semiurban,N

In [4]:
df.describe() # it use to finding all thing

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,100.000000,100.00000,50.000000,79.000000,70.000000
mean,12617.790000,5102.57000,337.220000,325.822785,0.471429
std,6588.612817,2956.14405,174.074496,108.138178,0.502787
min,1658.000000,23.00000,54.000000,180.000000,0.000000
25%,6756.750000,2806.75000,182.000000,240.000000,0.000000
50%,12325.000000,5143.50000,304.000000,360.000000,0.000000
75%,17729.000000,7691.00000,458.000000,360.000000,1.000000
max,24965.000000,9900.00000,694.000000,480.000000,1.000000

In [5]:
df.dtypes

Loan_ID                  str
Gender                   str
Married                  str
Dependents               str
Education                str
Self_Employed            str
ApplicantIncome        int64
CoapplicantIncome      int64
LoanAmount           float64
Loan_Amount_Term     float64
Credit_History       float64
Property_Area            str
Loan_Status              str
dtype: object

In [6]:
# Handling missing value

# df.isnull() # finding all values missing value

df.isnull().any(axis=1)

0      True
1      True
2      True
3      True
4     False
      ...
95    False
96     True
97     True
98     True
99     True
Length: 100, dtype: bool

In [7]:
# to finding total values in total row and coloumn
df.isnull().sum()

Loan_ID               0
Gender               23
Married              33
Dependents           20
Education             0
Self_Employed        37
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           50
Loan_Amount_Term     21
Credit_History       30
Property_Area         0
Loan_Status           0
dtype: int64

In [8]:
df.fillna(0)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP00100,Female,0,1,Not Graduate,No,17813,4645,488.0,0.0,0.0,Semiurban,Y
1,LP00101,Female,No,1,Not Graduate,0,22859,3364,0.0,480.0,0.0,Urban,N
2,LP00102,Male,Yes,2,Not Graduate,Yes,22555,6803,0.0,240.0,0.0,Semiurban,N
3,LP00103,Female,Yes,2,Not Graduate,0,4177,3235,0.0,240.0,1.0,Semiurban,N
4,LP00104,Male,No,0,Graduate,No,3175,3400,244.0,480.0,0.0,Semiurban,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,LP00195,Male,No,2,Graduate,Yes,16302,879,694.0,480.0,0.0,Rural,Y
96,LP00196,0,0,0,Graduate,0,15028,9900,54.0,240.0,0.0,Urban,Y
97,LP00197,0,0,2,Not Graduate,0,9481,5804,0.0,240.0,1.0,Semiurban,N
98,LP00198,Male,No,2,Not Graduate,0,17057,4682,186.0,480.0,0.0,Rural,Y
99,LP00199,Male,Yes,3+,Not Graduate,Yes,19666,9312,0.0,480.0,0.0,Urban,N

In [9]:
### Filling all mising values with the mean of column
df['LoanAmount_Fillna']=df['LoanAmount'].fillna(df['LoanAmount'].mean())
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,LoanAmount_Fillna
0,LP00100,Female,NaN,1,Not Graduate,No,17813,4645,488.0,NaN,NaN,Semiurban,Y,488.00
1,LP00101,Female,No,1,Not Graduate,NaN,22859,3364,NaN,480.0,0.0,Urban,N,337.22
2,LP00102,Male,Yes,2,Not Graduate,Yes,22555,6803,NaN,240.0,NaN,Semiurban,N,337.22
3,LP00103,Female,Yes,2,Not Graduate,NaN,4177,3235,NaN,240.0,1.0,Semiurban,N,337.22
4,LP00104,Male,No,0,Graduate,No,3175,3400,244.0,480.0,0.0,Semiurban,N,244.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,LP00195,Male,No,2,Graduate,Yes,16302,879,694.0,480.0,0.0,Rural,Y,694.00
96,LP00196,NaN,NaN,NaN,Graduate,NaN,15028,9900,54.0,240.0,0.0,Urban,Y,54.00
97,LP00197,NaN,NaN,2,Not Graduate,NaN,9481,5804,NaN,240.0,1.0,Semiurban,N,337.22
98,LP00198,Male,No,2,Not Graduate,NaN,17057,4682,186.0,480.0,NaN,Rural,Y,186.00
99,LP00199,Male,Yes,3+,Not Graduate,Yes,19666,9312,NaN,480.0,NaN,Urban,N,337.22

In [10]:
df['Gender_name'] = df['Gender'].fillna(df['Gender'].mode()[0])
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,LoanAmount_Fillna,Gender_name
0,LP00100,Female,NaN,1,Not Graduate,No,17813,4645,488.0,NaN,NaN,Semiurban,Y,488.00,Female
1,LP00101,Female,No,1,Not Graduate,NaN,22859,3364,NaN,480.0,0.0,Urban,N,337.22,Female
2,LP00102,Male,Yes,2,Not Graduate,Yes,22555,6803,NaN,240.0,NaN,Semiurban,N,337.22,Male
3,LP00103,Female,Yes,2,Not Graduate,NaN,4177,3235,NaN,240.0,1.0,Semiurban,N,337.22,Female
4,LP00104,Male,No,0,Graduate,No,3175,3400,244.0,480.0,0.0,Semiurban,N,244.00,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,LP00195,Male,No,2,Graduate,Yes,16302,879,694.0,480.0,0.0,Rural,Y,694.00,Male
96,LP00196,NaN,NaN,NaN,Graduate,NaN,15028,9900,54.0,240.0,0.0,Urban,Y,54.00,Male
97,LP00197,NaN,NaN,2,Not Graduate,NaN,9481,5804,NaN,240.0,1.0,Semiurban,N,337.22,Male
98,LP00198,Male,No,2,Not Graduate,NaN,17057,4682,186.0,480.0,NaN,Rural,Y,186.00,Male
99,LP00199,Male,Yes,3+,Not Graduate,Yes,19666,9312,NaN,480.0,NaN,Urban,N,337.22,Male

In [11]:
df['Credit_History'] = df['Credit_History']. astype(str)# Here to you convert float to str
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,LoanAmount_Fillna,Gender_name
0,LP00100,Female,NaN,1,Not Graduate,No,17813,4645,488.0,NaN,NaN,Semiurban,Y,488.00,Female
1,LP00101,Female,No,1,Not Graduate,NaN,22859,3364,NaN,480.0,0.0,Urban,N,337.22,Female
2,LP00102,Male,Yes,2,Not Graduate,Yes,22555,6803,NaN,240.0,NaN,Semiurban,N,337.22,Male
3,LP00103,Female,Yes,2,Not Graduate,NaN,4177,3235,NaN,240.0,1.0,Semiurban,N,337.22,Female
4,LP00104,Male,No,0,Graduate,No,3175,3400,244.0,480.0,0.0,Semiurban,N,244.00,Male
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,LP00195,Male,No,2,Graduate,Yes,16302,879,694.0,480.0,0.0,Rural,Y,694.00,Male
96,LP00196,NaN,NaN,NaN,Graduate,NaN,15028,9900,54.0,240.0,0.0,Urban,Y,54.00,Male
97,LP00197,NaN,NaN,2,Not Graduate,NaN,9481,5804,NaN,240.0,1.0,Semiurban,N,337.22,Male
98,LP00198,Male,No,2,Not Graduate,NaN,17057,4682,186.0,480.0,NaN,Rural,Y,186.00,Male
99,LP00199,Male,Yes,3+,Not Graduate,Yes,19666,9312,NaN,480.0,NaN,Urban,N,337.22,Male

In [12]:
df['Credit_History_name'] = df['Credit_History'].fillna(df['Gender'].mode()[0]) #mode are use to frequntly  repeat value given  
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,LoanAmount_Fillna,Gender_name,Credit_History_name
0,LP00100,Female,NaN,1,Not Graduate,No,17813,4645,488.0,NaN,NaN,Semiurban,Y,488.00,Female,Male
1,LP00101,Female,No,1,Not Graduate,NaN,22859,3364,NaN,480.0,0.0,Urban,N,337.22,Female,0.0
2,LP00102,Male,Yes,2,Not Graduate,Yes,22555,6803,NaN,240.0,NaN,Semiurban,N,337.22,Male,Male
3,LP00103,Female,Yes,2,Not Graduate,NaN,4177,3235,NaN,240.0,1.0,Semiurban,N,337.22,Female,1.0
4,LP00104,Male,No,0,Graduate,No,3175,3400,244.0,480.0,0.0,Semiurban,N,244.00,Male,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,LP00195,Male,No,2,Graduate,Yes,16302,879,694.0,480.0,0.0,Rural,Y,694.00,Male,0.0
96,LP00196,NaN,NaN,NaN,Graduate,NaN,15028,9900,54.0,240.0,0.0,Urban,Y,54.00,Male,0.0
97,LP00197,NaN,NaN,2,Not Graduate,NaN,9481,5804,NaN,240.0,1.0,Semiurban,N,337.22,Male,1.0
98,LP00198,Male,No,2,Not Graduate,NaN,17057,4682,186.0,480.0,NaN,Rural,Y,186.00,Male,Male
99,LP00199,Male,Yes,3+,Not Graduate,Yes,19666,9312,NaN,480.0,NaN,Urban,N,337.22,Male,Male

In [13]:
df.dtypes

Loan_ID                    str
Gender                     str
Married                    str
Dependents                 str
Education                  str
Self_Employed              str
ApplicantIncome          int64
CoapplicantIncome        int64
LoanAmount             float64
Loan_Amount_Term       float64
Credit_History             str
Property_Area              str
Loan_Status                str
LoanAmount_Fillna      float64
Gender_name                str
Credit_History_name        str
dtype: object

In [14]:
# Renameing Column
df =df.rename(columns={'Dependents':'Depending_val'})
df

,Loan_ID,Gender,Married,Depending_val,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,LoanAmount_Fillna,Gender_name,Credit_History_name
0,LP00100,Female,NaN,1,Not Graduate,No,17813,4645,488.0,NaN,NaN,Semiurban,Y,488.00,Female,Male
1,LP00101,Female,No,1,Not Graduate,NaN,22859,3364,NaN,480.0,0.0,Urban,N,337.22,Female,0.0
2,LP00102,Male,Yes,2,Not Graduate,Yes,22555,6803,NaN,240.0,NaN,Semiurban,N,337.22,Male,Male
3,LP00103,Female,Yes,2,Not Graduate,NaN,4177,3235,NaN,240.0,1.0,Semiurban,N,337.22,Female,1.0
4,LP00104,Male,No,0,Graduate,No,3175,3400,244.0,480.0,0.0,Semiurban,N,244.00,Male,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,LP00195,Male,No,2,Graduate,Yes,16302,879,694.0,480.0,0.0,Rural,Y,694.00,Male,0.0
96,LP00196,NaN,NaN,NaN,Graduate,NaN,15028,9900,54.0,240.0,0.0,Urban,Y,54.00,Male,0.0
97,LP00197,NaN,NaN,2,Not Graduate,NaN,9481,5804,NaN,240.0,1.0,Semiurban,N,337.22,Male,1.0
98,LP00198,Male,No,2,Not Graduate,NaN,17057,4682,186.0,480.0,NaN,Rural,Y,186.00,Male,Male
99,LP00199,Male,Yes,3+,Not Graduate,Yes,19666,9312,NaN,480.0,NaN,Urban,N,337.22,Male,Male

In [18]:
# Chending data type
df['Credit_History'] = df['Credit_History']. astype(str)# Here to you convert float to str
df

,Loan_ID,Gender,Married,Depending_val,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,LoanAmount_Fillna,Gender_name,Credit_History_name,New_Loan
0,LP00100,Female,NaN,1,Not Graduate,No,17813,4645,488.0,NaN,NaN,Semiurban,Y,488.00,Female,Male,NaN
1,LP00101,Female,No,1,Not Graduate,NaN,22859,3364,NaN,480.0,0.0,Urban,N,337.22,Female,0.0,960.0
2,LP00102,Male,Yes,2,Not Graduate,Yes,22555,6803,NaN,240.0,NaN,Semiurban,N,337.22,Male,Male,480.0
3,LP00103,Female,Yes,2,Not Graduate,NaN,4177,3235,NaN,240.0,1.0,Semiurban,N,337.22,Female,1.0,480.0
4,LP00104,Male,No,0,Graduate,No,3175,3400,244.0,480.0,0.0,Semiurban,N,244.00,Male,0.0,960.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,LP00195,Male,No,2,Graduate,Yes,16302,879,694.0,480.0,0.0,Rural,Y,694.00,Male,0.0,960.0
96,LP00196,NaN,NaN,NaN,Graduate,NaN,15028,9900,54.0,240.0,0.0,Urban,Y,54.00,Male,0.0,480.0
97,LP00197,NaN,NaN,2,Not Graduate,NaN,9481,5804,NaN,240.0,1.0,Semiurban,N,337.22,Male,1.0,480.0
98,LP00198,Male,No,2,Not Graduate,NaN,17057,4682,186.0,480.0,NaN,Rural,Y,186.00,Male,Male,960.0
99,LP00199,Male,Yes,3+,Not Graduate,Yes,19666,9312,NaN,480.0,NaN,Urban,N,337.22,Male,Male,960.0

In [22]:
df['New_Loan']=df['Loan_Amount_Term'].apply(lambda x:x*2) # lambda ek short / anonymous function hota hai.
df.head()

,Loan_ID,Gender,Married,Depending_val,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,LoanAmount_Fillna,Gender_name,Credit_History_name,New_Loan
0,LP00100,Female,NaN,1,Not Graduate,No,17813,4645,488.0,NaN,NaN,Semiurban,Y,488.00,Female,Male,NaN
1,LP00101,Female,No,1,Not Graduate,NaN,22859,3364,NaN,480.0,0.0,Urban,N,337.22,Female,0.0,960.0
2,LP00102,Male,Yes,2,Not Graduate,Yes,22555,6803,NaN,240.0,NaN,Semiurban,N,337.22,Male,Male,480.0
3,LP00103,Female,Yes,2,Not Graduate,NaN,4177,3235,NaN,240.0,1.0,Semiurban,N,337.22,Female,1.0,480.0
4,LP00104,Male,No,0,Graduate,No,3175,3400,244.0,480.0,0.0,Semiurban,N,244.00,Male,0.0,960.0

In [24]:
df.dtypes

Loan_ID                    str
Gender                     str
Married                    str
Depending_val              str
Education                  str
Self_Employed              str
ApplicantIncome          int64
CoapplicantIncome        int64
LoanAmount             float64
Loan_Amount_Term       float64
Credit_History             str
Property_Area              str
Loan_Status                str
LoanAmount_Fillna      float64
Gender_name                str
Credit_History_name        str
New_Loan               float64
dtype: object

In [27]:
# Data agrigating and grupping

group_mean =df.groupby('Loan_ID')['CoapplicantIncome'].mean()
print(group_mean)

Loan_ID
LP00100    4645.0
LP00101    3364.0
LP00102    6803.0
LP00103    3235.0
LP00104    3400.0
            ...
LP00195     879.0
LP00196    9900.0
LP00197    5804.0
LP00198    4682.0
LP00199    9312.0
Name: CoapplicantIncome, Length: 100, dtype: float64

In [28]:
# to finding total loan of sum that be 
gropup_sum=df.groupby(['CoapplicantIncome','ApplicantIncome'])['Loan_ID'].sum()
print(gropup_sum)

CoapplicantIncome  ApplicantIncome
23                 14602              LP00187
281                10073              LP00182
430                8546               LP00168
500                1658               LP00149
539                24317              LP00105
                                       ...
9711               3336               LP00106
9751               4163               LP00172
9758               5375               LP00123
9773               20252              LP00138
9900               15028              LP00196
Name: Loan_ID, Length: 100, dtype: str

In [33]:
# now be i call multiple agrigate fuctions call
group_agg =df.groupby('Loan_ID')['ApplicantIncome'].agg(['mean','std','median','count'])   
group_agg

            mean  std   median  count
Loan_ID
LP00100  17813.0  NaN  17813.0      1
LP00101  22859.0  NaN  22859.0      1
LP00102  22555.0  NaN  22555.0      1
LP00103   4177.0  NaN   4177.0      1
LP00104   3175.0  NaN   3175.0      1
...          ...  ...      ...    ...
LP00195  16302.0  NaN  16302.0      1
LP00196  15028.0  NaN  15028.0      1
LP00197   9481.0  NaN   9481.0      1
LP00198  17057.0  NaN  17057.0      1
LP00199  19666.0  NaN  19666.0      1

[100 rows x 4 columns]

In [51]:
# Merging and joing data frame
df1 =pd.DataFrame({"key":['A','B','C'], 'Value1':[1,2,3]})
df2 =pd.DataFrame({"key":['A','B','D'], 'Value2':[4,5,6]})

In [52]:
print(df1)
print(df2)

  key  Value1
0   A       1
1   B       2
2   C       3
  key  Value2
0   A       4
1   B       5
2   D       6

In [ ]:
# Merge data frame 'Key value'
# pd.merge(df1,df2,on="key",how="inner")

pd.merge(df1,df2,on="key",how="outer")  #when no value match given output will NAN

  key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [55]:
pd.merge(df1,df2,on="key",how="left")

  key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [56]:
pd.merge(df1,df2,on="key",how="right")

  key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6